"""Data models for story-seq."""

from typing import List, Optional
from pydantic import BaseModel, Field
from typing import Union

class SketchError(BaseModel):
    """Model for a file processing error during sketching."""
    error: str = Field(description="Description of the error that occurred.")
    
class RunSummary(BaseModel):
    """Fasta sketch. Summary of the FASTA sketch run."""
    total_input_files: int
    input_files_list: List[str]
    errors: List[SketchError]

class FileDetail(BaseModel):
    """Detailed sketch of a single, alphabet-uniform FASTA file."""
    source_file: str
    original_source: Optional[str] = None
    record_count: int
    total_length: int
    
class PartitionDetail(BaseModel):
    """A collection of files and aggregated stats for a single alphabet type."""
    total_records: int
    total_length: int
    average_length: float
    files: List[FileDetail]

class Partitions(BaseModel):
    """Container for the NT and AA partitions."""
    NT: PartitionDetail
    AA: PartitionDetail
    
class FastaSketch(BaseModel):
    """Top level fasta sketch. The definitive, structured model for the output of the fasta_sketch.py script."""
    run_summary: RunSummary
    partitions: Partitions

class AnalysisConfig(BaseModel):
    """
    Analysis configuration generated by the Configuration Agent.
    """
    identify_unknown_dna: bool = False
    find_protein_homologs: bool = False
    functional_hint: bool = False
    custom_other: bool = False
    fast_sketch: FastaSketch 


class BlastHit(BaseModel):
    """Model for a single BLAST hit."""
    
    query_id: str = Field(description="Query sequence identifier")
    subject_id: str = Field(description="Subject sequence identifier")
    identity: float = Field(ge=0, le=100, description="Percent identity")
    alignment_length: int = Field(gt=0, description="Alignment length")
    evalue: float = Field(ge=0, description="E-value")
    bit_score: float = Field(ge=0, description="Bit score")
    query_start: int = Field(gt=0, description="Query sequence start position")
    query_end: int = Field(gt=0, description="Query sequence end position")
    subject_start: int = Field(gt=0, description="Subject sequence start position")
    subject_end: int = Field(gt=0, description="Subject sequence end position")


class BlastResult(BaseModel):
    """Model for BLAST search results."""
    query_length: int = Field(gt=0, description="Length of query sequence")
    hits: List[BlastHit] = Field(default_factory=list, description="List of BLAST hits")
    database: str = Field(description="Database searched")
    
    @property
    def num_hits(self) -> int:
        """Return the number of hits."""
        return len(self.hits)
    
    @property
    def top_hit(self) -> Optional[BlastHit]:
        """Return the top hit by bit score."""
        if not self.hits:
            return None
        return max(self.hits, key=lambda x: x.bit_score)


class SequenceNarrative(BaseModel):
    """Model for AI-generated sequence narrative."""
    
    sequence_id: str = Field(description="Sequence identifier")
    narrative: str = Field(description="Generated narrative text")
    confidence: float = Field(ge=0, le=1, description="Confidence score")
    sources: List[str] = Field(
        default_factory=list,
        description="Sources used for narrative generation"
    )
